branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: nextjs-starter
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: gha-team13
  repository: null
  sc: null
  workspace_type: Application
